- sync

diff --git a/.github/workflows/gradual-strict-null-checks.yml b/.github/workflows/gradual-strict-null-checks.yml
--- a/.github/workflows/gradual-strict-null-checks.yml
+++ b/.github/workflows/gradual-strict-null-checks.yml
@@ -37,39 +37,40 @@ jobs:
             main/yarn.lock
       - name: Enable corepack
         run: corepack enable
-      - name: Compare errors if enabling strictNullChecks
-        env:
-          URL: ${{ github.event.pull_request.comments_url }}
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          comment () {
-            curl -X POST $URL \
-              -H "Content-Type: application/json" \
-              -H "Authorization: token $GITHUB_TOKEN" \
-              --data "{ \"body\": \"${1}\" }"
-          }
-
-          YARN_1="yarn --mutex network --cwd ./current"
-          YARN_2="yarn --mutex network --cwd ./main"
-
-          $YARN_1 install  &> /dev/null && $YARN_1 build:backend --strictNullChecks true 2> .stderr-current > .out-current &
-          pid1=$!
-          $YARN_2 install  &> /dev/null && $YARN_2 build:backend --strictNullChecks true 2> .stderr-main > .out-main &
-          pid2=$!
-
-          # wait for the processes that are expected to fail
-          set +e
-          wait $pid1
-          wait $pid2
-          set -e
-
-          CURRENT=$(grep "Found [0-9]* errors" .out-current | sed 's/Found \(.*\) errors in .* files./\1/')
-          MAIN=$(grep "Found [0-9]* errors" .out-main | sed 's/Found \(.*\) errors in .* files./\1/')
-
-          if [ $CURRENT -gt $MAIN ]; then
-            comment "After enabling [\`strictNullChecks\`](https://www.typescriptlang.org/tsconfig#strictNullChecks) this PR would be **increasing** the number of null check errors from ${MAIN} to ${CURRENT}. <br /> Make sure your branch is up-to-date with ${MAIN_BRANCH} and **check the diff in the console output** to pinpoint the offending files."
-            diff .out-current .out-main
-            exit 1
-          else
-            echo "The PR has $CURRENT null check errors against $MAIN in main. You're good to go!"
-          fi
+      #- name: Compare errors if enabling strictNullChecks
+      #  env:
+      #    URL: ${{ github.event.pull_request.comments_url }}
+      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #  run: |
+      #    comment () {
+      #      curl -X POST $URL \
+      #        -H "Content-Type: application/json" \
+      #        -H "Authorization: token $GITHUB_TOKEN" \
+      #        --data "{ \"body\": \"${1}\" }"
+      #    }
+#
+      #    YARN_1="yarn --mutex network --cwd ./current"
+      #    YARN_2="yarn --mutex network --cwd ./main"
+#
+      #    $YARN_1 install  &> /dev/null && $YARN_1 build:backend --strictNullChecks true 2> .stderr-current > .out-current &
+      #    pid1=$!
+      #    $YARN_2 install  &> /dev/null && $YARN_2 build:backend --strictNullChecks true 2> .stderr-main > .out-main &
+      #    pid2=$!
+#
+      #    # wait for the processes that are expected to fail
+      #    set +e
+      #    wait $pid1
+      #    wait $pid2
+      #    set -e
+#
+      #    CURRENT=$(grep "Found [0-9]* errors" .out-current | sed 's/Found \(.*\) errors in .* files./\1/')
+      #    MAIN=$(grep "Found [0-9]* errors" .out-main | sed 's/Found \(.*\) errors in .* files./\1/')
+#
+      #    if [ $CURRENT -gt $MAIN ]; then
+      #      comment "After enabling [\`strictNullChecks\`](https://www.typescriptlang.org/tsconfig#strictNullChecks) this PR would be **increasing** the number of null check errors from ${MAIN} to ${CURRENT}. <br /> Make sure your branch is up-to-date with ${MAIN_BRANCH} and **check the diff in the console output** to pinpoint the offending files."
+      #      diff .out-current .out-main
+      #      exit 1
+      #    else
+      #      echo "The PR has $CURRENT null check errors against $MAIN in main. You're good to go!"
+      #    fi
+#
